### ISSUE TITLE
how to implement a whitelist?

### ISSUE THREAD

**Issue by TheFlipside** [gmellini/squidproxy-conf#1]
hello, your configuration set is very useful.

i'm trying to figure out how to use a whitelist.

i have set the following before  "http_access deny all":

**acl whitelist dstdomain "/etc/squid/whitelist.conf"**
**http_access allow whitelist**

and the file "/etc/squid/whitelist.conf" contains
**.google.com**

i expected with this setup the clients using the proxy would only be able to access the url google.com
but they still have unlimited access to all urls

what is the correct way to set a whitelist?

**Comment by gmellini** [comment]
In the repo the whitelist mechanism is just for SSL/TLS inspection (how to skip inspection for some website).
Your question is about squid general whitelist configuration and is not repo related. 
Closing

**Comment by TheFlipside** [comment]
i'll answer it myself

the only thing i missed was to comment out
**http_access allow localnet**
and
**http_access allow localhost**

==>
**# http_access allow localnet**
**# http_access allow localhost**

the whitelist was then applied
